trigger:
- master
pool:
  vmImage: 'Ubuntu-20.04'
steps:
- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'npm'
    targetRepo: 'dinesh-npm-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'npm'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "/home/vsts/work/1/s/npm-example-0.0.3.tgz",
            "target": "harish-npm-local/level1/level2/npm-example-0.0.3.tgz"
          }
        ]
      }
    failNoOp: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -lart *'