pool:
  vmImage: 'ubuntu-20.04'
steps:
- task: JFrogNpm@1
  inputs:
    command: 'custom'
    customCommandAndArgs: 'pack'
    artifactoryConnection: 'shivani'
    sourceRepo: 'shivani-npm'
    targetRepo: 'shivani-npm-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'shivani'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "npm-example-0.0.3.tgz",
            "target": "shivani-npm-local/folder1/folder2/npm-example-0.0.3.tgz"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true