trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'
steps:
- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'npm'
    targetRepo: 'dinesh-npm-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -lart *'