trigger:
 - master
steps:
- task: JFrogNpm@1
  inputs:
    command: 'ci'
    artifactoryConnection: 'dinesh'
    sourceRepo: 'dinesh-npm'
    collectBuildInfo: true
    arguments: '--verbose'
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'dinesh'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'dinesh1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true