trigger:
- master
pool:
  vmImage: 'Ubuntu-20.04'
steps:
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'npm'
    sourceRepo: 'harish-npm-virtual'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'find / -name npm-example-0.0.3.tgz'
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'npm'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "$(System.ArtifactsDirectory)/npm-example-0.0.3.tgz",
            "target": "harish-npm-local/level1/level2/npm-example-0.0.3.tgz"
          }
        ]
      }
    failNoOp: true
