pool:
  vmImage: 'ubuntu-20.04'
steps:
- task: JFrogNpm@1
  inputs:
    command: 'custom'
    customCommandAndArgs: 'pack'
    artifactoryConnection: 'shivani'
    sourceRepo: 'shivani-npm'
    targetRepo: 'shivani-npm-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo find / -name npm-example-0.0.3.tgz'